import fs from "node:fs";
process.env.PP_DATA_DIR = ".data-replay";
fs.rmSync(".data-replay", { recursive: true, force: true });
const { createBiosphere, step, creditExternalCall, populationRoot, honesty } = await import("./src/life.js");
const rec = await import("./src/recorder.js");
const bio = createBiosphere({ seed: "0xfeedfacecafe", name: "Replay Test", founders: 24, tickLabel: "hour" });
rec.writeGenesis(bio, { note: "e2e determinism test" });
step(bio, 20);
rec.record(bio, { kind: "serve", niche: "keccak", usd: 0.5, buyer: "0xb0b", txHash: "0xaa", subsidized: false });
creditExternalCall(bio, "keccak", { revenue: 0.5, calls: 1, buyer: "0xb0b", txHash: "0xaa", subsidized: false });
step(bio, 20);
rec.record(bio, { kind: "demand", niche: "oracle", usd: 1.0, units: 250, chunks: 10, buyer: "0xoperator", subsidized: true });
for (let i = 0; i < 10; i++) creditExternalCall(bio, "oracle", { revenue: 0.1, calls: 25, buyer: "0xoperator", subsidized: true });
step(bio, 20);
rec.record(bio, { kind: "credit", niche: "render", revenue: 0.25, calls: 2, buyer: "0xalice", subsidized: false });
creditExternalCall(bio, "render", { revenue: 0.25, calls: 2, buyer: "0xalice", subsidized: false });
step(bio, 40);
const root = populationRoot(bio);
const h = honesty(bio);
fs.writeFileSync(".data-replay/expected.json", JSON.stringify({ tick: bio.meta.tick, alive: bio.organisms.size, gen: bio.counters.generations, root, honesty: h }, null, 2));
console.log("live  : tick=" + bio.meta.tick + " alive=" + bio.organisms.size + " gen=" + bio.counters.generations);
console.log("root  : " + root);
console.log("honest: real=$" + h.realRevenueUSDC + " subsidy=$" + h.subsidyUSDC + " ratio=" + h.realRevenueRatioBps + "bps simShare=" + h.simulatedDemandShareBps + "bps");
console.log("inputs: " + rec.loadInputs().length + " 条已记录 · genesis=" + rec.GENESIS);
